### ISSUE TITLE
Currently can't build on Linux (missing OpenGL)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyopengl-feedstock#1]
Related comment ( https://github.com/conda-forge/staged-recipes/pull/327#discussion_r59378775 ).

This issue is merely a formality to document what is going on. The fix is already known.

Basically, we need to have OpenGL installed to test on Linux. This can be done either of two ways.

1. Hack in a `yum` install for the OpenGL dependency as explained in [this comment]( https://github.com/conda-forge/pyopengl-feedstock/commit/76763de01ec484bd23fdc6bce99032c4377fa9ee#commitcomment-17076003 ).
2. Add the dependency to the Docker image as is done with this PR ( https://github.com/pelson/Obvious-CI/pull/63 ).

For now, let's see if the Docker PR gets accepted. If it does, there is nothing to do here. If it doesn't, we need to pursue option 1.

**Comment by pelson** [comment]
I has always been my intention to support this ability in the [https://github.com/conda-forge/pyopengl-feedstock/blob/master/conda-forge.yml](conda-forge.yml)\* metadata, but we have so far managed to dodge the bullet. So my option 3 is:

3\. Add OpenGL to the metadata, and upgrade conda-smithy to deal with the extra yum requirement


\* a thought needs to happen with regards to where it goes - I can see arguments for conda-forge.yml and arguments for meta.yaml.

**Comment by jakirkham** [comment]
Thanks. My reply can be found in [this comment]( https://github.com/conda-forge/conda-forge.github.io/issues/82#issuecomment-209260591 ) in this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/82 ) regarding the use of `yum`.

**Comment by jakirkham** [comment]
Also, as I expect this may take some time, point 1 is meant as a temporary workaround until we come up with a better solution for `yum` requirements. So, certainly it will be replaced by something better at some point.
