### ISSUE TITLE
error on env activation

### ISSUE THREAD

**Issue by beckermr** [conda-forge/pyopengl-feedstock#14]
Hi @conda-forge/pyopengl!

In a recipe rebuild here, https://github.com/conda-forge/xpdsim-feedstock/pull/6, there is an error on environment activation from this package. Can one you all investigate?

**Comment by almarklein** [comment]
Just made a PR to push a new version and rerender. Maybe that will help. Do you happpen to know why CI does not kick in for that PR (I have not been very active with conda-forge lately).

**Comment by almarklein** [comment]
> Do you happpen to know why CI does not kick in for that PR [...]?

Nevermind

**Comment by almarklein** [comment]
PR merged, the new build is available on anaconda.org

**Comment by CJ-Wright** [comment]
It seems that the new version has not fixed the issue `conda.CondaMultiError: post-link script failed for package conda-forge::pyopengl-3.1.3b2-py_0`

**Comment by beckermr** [comment]
So this is a change in the CI environment? Conda depending on stuff out of itself is a necessary evil...

**Comment by CJ-Wright** [comment]
Yea something tells me we can ship our own drivers.

**Comment by almarklein** [comment]
Would it help if we print the warning and then `exit 0` instead?

**Comment by beckermr** [comment]
Not if it leaves the env broken. We probably need to package the driver if possible.

**Comment by CJ-Wright** [comment]
Maybe have a CDT? Currently I'm trying to mitigate this by removing this package where it is an optional dependency in my tree.

**Comment by beckermr** [comment]
Hrrmmmmm. Anaconda docs indicate that the CDT for OpenGL is under discussion. I think we have hit a thing that is already a thing. 

https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#cdt-packages

**Comment by jaimergp** [comment]
Closed by #21
