### ISSUE TITLE
Error in postlink script 

### ISSUE THREAD

**Issue by renefritze** [conda-forge/pyopengl-feedstock#18]
Issue: I get conda [build errors](https://circleci.com/gh/conda-forge/staged-recipes/34324?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with pyopengl as a dependency in a [new recipe](https://github.com/conda-forge/staged-recipes/pull/7669) on conda-forge. 

The build environment is that of the conda-forge/staged-recipes repository on circleci, which I have no real access to. Relevant info could be that linked build log though.

**Comment by almarklein** [comment]
Seems related to #14: the build script fails if the environment does not have OpenGL drivers.

**Comment by renefritze** [comment]
I see. That fits with my recipe only failing on linux (circleci) with this error. I guess I should try again then once #14 is resolved?

**Comment by renefritze** [comment]
In [my PR](https://github.com/conda-forge/staged-recipes/pull/7669) I was advised to install `mesa-libGL-devel`, which got me past this problem. I think I'm ok with that solution, so if #14 covers this issue anyways, maybe close this here?
